version: '3'

services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  express:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3060:3060"
    depends_on:
      - mongodb

  react:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "30:61"
    depends_on:
      - express

volumes:
  mongodb_data:
