services:
  3006frontendReact:
    build:
      context: .
      dockerfile: Dockerfile.reactUI
    ports:
      - "3000:3000"   
    depends_on:
      - db
  3006backendNode:
    build:
      context: ./server
      dockerfile: Dockerfile.node
    ports:
      - "9000:9000"   
    depends_on:
      - db
  db:
    volumes:
      - slack_db:/data/db
    image: mongo:latest
    ports:
      - "27017:27017" 
volumes:
   slack_db: