version: '3'

services:

  mongodb:
    image: mongo:latest
    container_name: 3006-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db
      
  express:
    build:
      context: ./server
    container_name: 3006-express
    ports:
      - "3001:3001"
    depends_on:
      - mongodb

  react:
    build:
      context: ./client
    container_name: 3006-react
    ports:
      - "3000:3000"
    depends_on:
      - express
            
volumes:
  mongodb-data: